config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'project/index'
  

  get 'project/edit'
  
  

  get 'project/show'

  get 'project/show_task'
 post 'project/show_task'
  get 'project/update_all_task'
  post 'project/update_all_task'

  resources :project
  root 'project#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
 
    has_many :tasks, :dependent => :destroy  
  accepts_nested_attributes_for :tasks, allow_destroy: true
  validates :title, presence: true, length: { maximum: 30, minimum:5 }                  
    validates :desc, presence: true    
    #attr_accessor :tasks_attributes
    validates_associated :tasks
    #validates_presence_of :tasks
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  before_action :authenticate_user!
  def index
    @projects=Project.paginate(:page => params[:page], :per_page => 4) 
    @project=Project.new
  end

  def create         
    @project=Project.new(project_params)
	  if @project.save
      render :json => @project
    else
      render :json => { :errors => @project.errors.full_messages }, :status => 422
    end
  end

  def new
    @project = Project.new   
    #@project.tasks.build
  end

  def edit
    @project = Project.find(params[:id])  
  end

  def update    
    @project = Project.find(params[:id])
	  if @project.update(project_params)
	    redirect_to @project, notice: "Project Update successsfully"   
	  else
	    render 'edit'
    end
  end

  def update_all_task   
    # @projects=Project.paginate(:page => params[:page], :per_page => 2) 
    #     @date=params[:obj][:date]         
    #     @task=params[:project][:tasks_attributes].values               
    #     val = JSON.parse(params[:project][:tasks_attributes].to_json)                
    #     value =Array.new                       
    #     value=val.values.each { |k| k.delete "_destroy" }                                                                         
    #     val_sum = value.inject(0) {|sum, hash| sum + hash["dur"].to_i}                                           
    #     rem =8-Task.where(:date => @date).sum("dur")            
    #     if val_sum > rem 
    #       if rem == 0
    #         render :json => { :errors => "Already Duration Time Complter for #{@date}" }, :status => 422         
    #       else 
    #         render :json => { :errors => "#{@date} have Remanining #{rem} hours" }, :status => 422           
    #       end                                 
    #     else           
    #       begin                                             
    #         #if value.map {|tax| @t=Task.new(tax).save!}            
    #        if Task.create!(value)            
    #         result=render_to_string(:partial => '/project/show_tasks', :locals => {:@projects => @projects})                    
    #         render :json => {success: "Tasks Added Sucessfully", project: result}           
    #        end                                              
    #       rescue ActiveRecord::RecordInvalid => invalid            
    #         render :json => { :errors => invalid.record.errors.full_messages }, :status => 422
    #       end                     
    #     end         
    @projects=Project.paginate(:page => params[:page], :per_page => 2)	 
	  @date=params[:obj][:date]
	  has_errors = false
	  value=Array.new
	  params[:project][:tasks_attributes].values.each do |tast_attr|
  		value << tast_attr.except("_destroy")
  	  @tasks = Task.new(tast_attr.except("_destroy"))
		  unless @tasks.valid?
			  has_errors=true
			  break
		  end
	  end
    val_sum = value.inject(0) {|sum, hash| sum + hash["dur"].to_i}
	  rem=8-Task.where(:date => @date).sum(:dur)	
	  if  val_sum > rem || has_errors==true
	  	if val_sum > rem
        if rem == 0
          render :json => { :errors => "Already Duration Time Complete for #{@date}" }, :status => 422         
        else 
         render :json => { :errors => "#{@date} have Remanining #{rem} hours" }, :status => 422           
        end  
		  else
			  render :json => { :errors => @tasks.errors.full_messages}, :status => 422
		  end
	  else	
		  if Task.create(value)
			  result=render_to_string(:partial => '/project/show_tasks', :locals => {:@projects => @projects})
			  render :json => {success: "Tasks Successfully Added", project: result}
		  end
	  end  
  end

  def show_task     
    @project= Project.new    
    @projects=Project.paginate(:page => params[:page], :per_page => 2) 
  end
  

  def show  
    @project = Project.find(params[:id])
    @task = Task.find_by_id params[:id]
  end

  def destroy
    @project = Project.find_by_id params[:id]
    @project.destroy  
    redirect_to root_path
  end

  private
		  def project_params
        params.require(:project).permit(:title, :desc, :tasks_attributes => [:id, :project_id, :date, :title, :desc, :dur, :_destroy])
      end 
      def task_params
        params.require(:project).require(:tasks_attributes).permit(:project_id, :date, :title, :desc, :dur, :_destroy)
      end               
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/project/_new.html.erb
<script>
$(document).ready(function(){
   $("#commit").click(function(event){            
         event.preventDefault(); 
          $.ajax({
            type: "post",
            url: $("form").attr('action'),
            data: $("form").serialize(),
            dataType: "json",
            success: function () 
            {
              $("#note").text("Project Sucessfully Added ").css('color', 'green');;
            },
             error: function(xhr)
            {              
              var errors = $.parseJSON(xhr.responseText).errors;
              var errorText;             
              errorText = "<center>There were errors with the submission: \n<ul>";
              for ( error in errors )
              {
                errorText += "<li>" + error + ': ' + errors[error] + "</li></center> ";
              }
              errorText += "</ul>";             
              $("#note").html(errorText).css('color','red');              
            }          
          });         
    });     
});
</script>
<div id="note"></div>
<%= nested_form_for @project, :url => {:action => "create", :controller => "project"}, :html => {:class => "organizer"} do |form| %> 
<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table cellpading=10 cellspacing=10 align='center' bgcolor='skyblue'>
<tr><th>
    <%= form.label :Title %></th><td>
    <%= form.text_field :title, value: params[:title] %></td></tr>
  
 
  <tr><th>
    <%= form.label :Description%></th><td>
    <%= form.text_area :desc %></td></tr>
  <tr><td colspan=2>
  <table id="tasks">
  <%= form.fields_for :tasks, :wrapper => false do |task_form| %>
    <tr class="fields">
    <td><%= task_form.date_field :date %></td>
      <td><%= task_form.text_field :title, placeholder: "Task Title" %></td>
       <td><%= task_form.text_field :desc, placeholder: "Task Description" %></td>
        <td><%= task_form.text_field :dur, placeholder: "Task Duration" %></td>
      <td><%= task_form.link_to_remove "Remove this task" %></td>
    </tr>
  <% end %>
</table>
<p><%= form.link_to_add "Add a task", :tasks, :data => { :target => "#tasks" } %></p>
</td></tr>
 <tr align="center"><td>
    <%= submit_tag "Create", data: { disable_with: "Please wait.." }, id: "commit" %><td>
  </tr></table>
 
<% end %>

app/views/project/_show_tasks.html.erb
<div id="panel">
<input id="search" type="text" placeholder="Search the Date..">

<table cellpadding=5 cellspacing=5 align=center>
<tr bgcolor='lime'><th>Project Name</th><th>Description</th><th>Tasks</th></tr>
<% @projects.each do |pro| %>
<tr><td><%= pro.title %></td>
<td><%= pro.desc %></td>
<td><table cellpadding=5 cellspacing=5>
    <thead><tr bgcolor='skyblue'><th>Date</th><th>Task</th><th>Description</th><th>Duration</th></tr></thead>
    <tbody id="myTable"><% pro.tasks.each do |tas| %>
    <tr><td><%= tas.date %></td><td><%= tas.title %></td><td><%=tas.desc %></td><td><%= tas.dur %></td></tr>
    <% end %></tbody></table>
    </td>
  </tr>
  <% end %>
  </table>
  <%= will_paginate @projects %>
  </div>

app/views/project/edit.html.erb
<center><h1>Edit a Project</h1></center>
<%= nested_form_for @project, :url => {:action => "update", :controller => "project"} do |form| %> 

<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table cellpading=20 cellspacing=20 align='center' bgcolor='skyblue'>
<tr><th>
    <%= form.label :Title %></th><td>
    <%= form.text_field :title %></td></tr>
  <tr><th>
    <%= form.label :Description%></th><td>
    <%= form.text_area :desc %></td></tr>
  <tr><td colspan=2>
  <table id="tasks">
  <%= form.fields_for :tasks, :wrapper => false do |task_form| %>
    <tr class="fields">
     <td><%= task_form.date_field :date %></td>
      <td><%= task_form.text_field :title, placeholder: "Task Title" %></td>
       <td><%= task_form.text_field :desc, placeholder: "Task Description" %></td>
        <td><%= task_form.text_field :dur, placeholder: "Task Duration" %></td>
      <td><%= task_form.link_to_remove "Remove this task" %></td>
    </tr>
  <% end %>
</table>
<p><%= form.link_to_add "Add a task", :tasks, :data => { :target => "#tasks" } %></p>
</td></tr>
 <tr align="center"><td>
 <%= link_to 'Back', project_index_path %></td><td>
    <%= form.submit %><td>
  </tr></table>
 
<% end %>

app/views/project/index.html.erb
<center><font color='lime'>
<h1>Time Sheet for Projects</h1></font>
  
Welcome<br><br>
<% if current_user.present? -%>
 <%= link_to "All Tasks", :controller => :project, :action => :show_task %> |
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %> <% end %> 
<center><h3>Create a Project</h3></center>

<%= render partial: "new" %>

<br>

 </center>
<table cellpadding=10 cellspacing=10 align=center id = "post_table">
  <tr>
    <th bgcolor='lime'>Title</th>
    <th bgcolor='lime'>Description</th>
    <th bgcolor='lime' colspan=3>CRUD</th>
  </tr>
 
  <% @projects.each do |p| %>
    <tr>
      <td><%= p.title %></td>
      <td><%= p.desc %></td>
      <td><%= link_to 'Show', project_path(p) %></td>
      <td><%= link_to 'Edit', edit_project_path(p) %></td>
       <td><%= link_to 'Destroy', project_path(p),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @projects %>

app/views/project/new.html.erb
<center><h1>Create a Project</h1></center>
<%= nested_form_for @project, :url => {:action => "create", :controller => "project"} do |form| %> 

<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table cellpading=20 cellspacing=20 align='center' bgcolor='skyblue'>
<tr><th>
    <%= form.label :Title %></th><td>
    <%= form.text_field :title %></td></tr>
  
 
  <tr><th>
    <%= form.label :Description%></th><td>
    <%= form.text_area :desc %></td></tr>
  <tr><td colspan=2>
  <table id="tasks">
  <%= form.fields_for :tasks, :wrapper => false do |task_form| %>
    <tr class="fields">
    <td><%= task_form.date_field :date %></td>
      <td><%= task_form.text_field :title, placeholder: "Task Title" %></td>
       <td><%= task_form.text_field :desc, placeholder: "Task Description" %></td>
        <td><%= task_form.text_field :dur, placeholder: "Task Duration" %></td>
      <td><%= task_form.link_to_remove "Remove this task" %></td>
    </tr>
  <% end %>
</table>
<p><%= form.link_to_add "Add a task", :tasks, :data => { :target => "#tasks" } %></p>
</td></tr>
 <tr align="center"><td>
 <%= link_to 'Back', project_index_path %></td><td>
    <%= form.submit %><td>
  </tr></table>
 
<% end %>

app/views/project/show.html.erb
<center><h1>Task Details </h1>
<%= link_to 'Back', project_index_path %>
<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @project.desc %>
</p>

app/views/project/show_task.html.erb
<script> 
$(document).ready(function(event){
  $("#search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });  
 
   $("#commit").click(function(event)
   {           
        var dat = $("#obj_date").val();              
        $('.form-date').val(dat);
        var sum = 0.0;        
          event.preventDefault();   
          $('.dur').each(function()
          {
            sum += parseFloat(this.value);        
          });      
          if(sum>8)
          {          
            $("#note").text("The Duration Time more than 8 hours..Please Check Duration Time").css('color', 'red');             
          } 
          else if (sum == 0)
          {
            $("#note").text("Please Fill the Form").css('color', 'red');                        
          }               
          else
          {
                   
           $.ajax({
            type: "post",
            url: $("form").attr('action'),          
            data: $("form").serialize(),            
            dataType: "json",
            success: function (response) 
            {
              //alert("success");
              if(response.success)
              {
              $("#note").text(response.success).css('color', 'green');
              $("form")[0].reset();             
              }   
              // if(response.error)          
              // {
              //   $("#note").text(response.error).css('color', 'red');
              // }
              if(response.project)
              {
                $("#panel").html(response.project);
              }
            },
             error: function(xhr)
            {   
                //alert("fail");
                //alert(xhr.responseText);
              var errors = $.parseJSON(xhr.responseText).errors;                                    
              $("#note").text(errors).css('color','red');              
            }          
          }); 
        }                           
  });               
});
</script>
<div id="note"></div>
<div id="flip"><h1><center>View All Tasks</center></h1></div>
<div align='center'>
<%= nested_form_for @project, :url => {:action => "update_all_task", :controller => "project"} do |form| %> 
<% if @date %>
<%= date_field(:obj, :date, :value => @date) %>
<% else %>
<%= date_field(:obj, :date) %>
<% end %>
<table id="tasks">
  <%= form.fields_for :tasks, :wrapper => false do |task_form| %>
    <tr class="fields">
    <td><%= task_form.hidden_field :date, class: 'form-date' %></td>
    <td><%= task_form.select :project_id, options_for_select(Project.all.map {|t| [ t.title, t.id]}, task_form.object.project_id), include_blank: "     " %></td>
      <td><%= task_form.text_field :title, placeholder: "Task Title", class: 'title' %></td>
        <td><%= task_form.text_field :desc, placeholder: "Task Description", class: 'desc' %></td>
        <td><%= task_form.number_field :dur, placeholder: "Task Duration", class: 'dur', step: :any %></td>
      <td><%= task_form.link_to_remove "Remove" %></td>
    </tr>
  <% end %>
</table>
<p><%= form.link_to_add "Add a task", :tasks, :data => { :target => "#tasks" } %></p>
<%= submit_tag "Add Task", data: { disable_with: "Please wait.." }, id: "commit" %>
<p><%= link_to 'Back', project_index_path %></p>
<% end %>
</div>
<%= render partial: "show_tasks" %>